apiVersion: v1
kind: ConfigMap
metadata:
  name: projectconfigmap
data:
  DB_NAME: projectdatabase
  DB_USER: projectuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpassword
type: Opaque
data:
  PASSWORD: cHJvamVjdHBhc3N3b3Jk